@baseUrl = http://localhost:3000/api

# Categories

# @name getAllCategories
GET {{baseUrl}}/categories

###

# @name addNewCategory
POST {{baseUrl}}/categories
Content-Type: application/json

{
    "name":"Món nướng"
}

###

# @name updateCategory
PATCH  {{baseUrl}}/categories/92478
Content-Type: application/json

{
    "name":"Món xào"
}

###

# @name deleteCategory
DELETE  {{baseUrl}}/categories/791530