@baseUrl = http://localhost:3000/api

# Categories

# @name getAllCategories
GET {{baseUrl}}/categories

###

# @name addNewCategory
POST {{baseUrl}}/categories
Content-Type: application/json

{
    "name":"Laptop"
}

###

# @name updateCategory
PATCH  {{baseUrl}}/categories/3d46b1ba-96f1-4cd9-b200-08ebcb725938
Content-Type: application/json

{
    "name":"Electronics new"
}

###

# @name deleteCategory
DELETE  {{baseUrl}}/categories/2