@baseUrl = http://localhost:3000/api
@resourceName = products

# Products

# @name getAll
GET {{baseUrl}}/{{resourceName}}

###

# @name filterProducts
GET http://192.168.9.104:3000/api/products?categoryId=1

###

# @name filterProductsLike
GET {{baseUrl}}/{{resourceName}}?nameProduct=Cơm hến Huế

###

# @name filterProducts
GET {{baseUrl}}/{{resourceName}}?id=1

###

# @name filterProducts
GET {{baseUrl}}/{{resourceName}}?color=red&price_gte=10

###

# @name pagination
GET {{baseUrl}}/{{resourceName}}?page=1&_limit=2

###

# @name sort
GET {{baseUrl}}/{{resourceName}}?_sort=price&_order=asc

###

# @name sortDescending
GET {{baseUrl}}/{{resourceName}}?_sort=price&_order=desc

###

# @name addNew
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
    "categoryId": "51af4f4f-695b-4f6f-8c8f-ca067cd5f7b0",
    "name": "Small Concrete Pizza",
    "color": "gold",
    "price": 555,
    "thumbnailUrl": "http://placeimg.com/600/400"
  }

###

# @name update
PATCH  {{baseUrl}}/{{resourceName}}/1
Content-Type: application/json

{
    "likeStatus": true
  }

###

# @name update likeStatus
PUT  http://192.168.9.104:3000/api/products/1
Content-Type: application/json

{
   "price": 20044040,
}

###


# @name remove
DELETE  {{baseUrl}}/{{resourceName}}/11